apiVersion: v1
kind: Service
metadata:
  name: {{ include "boltbase.fullname" . }}-coordinator
  labels:
    {{- include "boltbase.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  type: ClusterIP
  selector:
    {{- include "boltbase.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
  ports:
    - name: grpc
      port: 50055
      targetPort: grpc
      protocol: TCP
