apiVersion: v1
kind: Service
metadata:
  name: {{ include "dagu.fullname" . }}-scheduler
  labels:
    {{- include "dagu.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  type: ClusterIP
  selector:
    {{- include "dagu.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
  ports:
    - name: health
      port: 8090
      targetPort: health
      protocol: TCP
