apiVersion: v1
kind: Service
metadata:
  name: {{ include "dagu.fullname" . }}-ui
  labels:
    {{- include "dagu.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  selector:
    {{- include "dagu.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
